<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Feeds\Module'                     => __DIR__ . '/Module.php',
    'Feeds\Controller\IndexController' => __DIR__ . '/src/Feeds/Controller/IndexController.php',
    'Feeds\Entity\Article'             => __DIR__ . '/src/Feeds/Entity/Article.php',
    'Feeds\Entity\Feed'                => __DIR__ . '/src/Feeds/Entity/Feed.php',
    'Feeds\Forms\SubscribeForm'        => __DIR__ . '/src/Feeds/Forms/SubscribeForm.php',
    'Feeds\Forms\UnsubscribeForm'      => __DIR__ . '/src/Feeds/Forms/UnsubscribeForm.php',
);
