<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Common\Module'                     => __DIR__ . '/Module.php',
    'Common\View\Helper\FlashMessenger' => __DIR__ . '/src/Common/View/Helper/FlashMessenger.php',
);
