<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Common\Module'                     => __DIR__ . '/Module.php',
    'Common\Controller\IndexController' => __DIR__ . '/src/Common/Controller/IndexController.php',
);
