<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Wall\Module'                     => __DIR__ . '/Module.php',
    'Wall\Controller\IndexController' => __DIR__ . '/src/Wall/Controller/IndexController.php',
    'Wall\Entity\Image'               => __DIR__ . '/src/Wall/Entity/Image.php',
    'Wall\Entity\Status'              => __DIR__ . '/src/Wall/Entity/Status.php',
    'Wall\Forms\ImageForm'            => __DIR__ . '/src/Wall/Forms/ImageForm.php',
    'Wall\Forms\TextStatusForm'       => __DIR__ . '/src/Wall/Forms/TextStatusForm.php',
);
