<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Wall\Module'                     => __DIR__ . '/Module.php',
    'Wall\Controller\IndexController' => __DIR__ . '/src/Wall/Controller/IndexController.php',
);
