<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Api\Module'           => __DIR__ . '/Module.php',
    'Api\Client\ApiClient' => __DIR__ . '/src/Api/Client/ApiClient.php',
);
