<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                     => __DIR__ . '/Module.php',
    'Users\Controller\IndexController' => __DIR__ . '/src/Users/Controller/IndexController.php',
    'Users\Entity\User'                => __DIR__ . '/src/Users/Entity/User.php',
    'Users\Forms\SignupForm'           => __DIR__ . '/src/Users/Forms/SignupForm.php',
);
